# week08/k8s/frontend.yaml

# week08/k8s/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: { app: frontend }
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
        - name: frontend              # <- must be 'frontend'
          image: nginx:alpine         # placeholder; CD sets ACR image
          imagePullPolicy: IfNotPresent
          ports: [ { containerPort: 80 } ]
          readinessProbe: { httpGet: { path: /, port: 80 }, initialDelaySeconds: 5, periodSeconds: 10 }
          livenessProbe:  { httpGet: { path: /, port: 80 }, initialDelaySeconds: 10, periodSeconds: 20 }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend                     # <- must be 'frontend'
  labels: { app: frontend }
spec:
  type: LoadBalancer
  selector: { app: frontend }
  ports:
    - name: http
      port: 80
      targetPort: 80
