# week08/k8s/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        # MUST be 'frontend' so the CD step "kubectl set image deploy/frontend frontend=..." works
        - name: frontend
          # Placeholder image; the CD workflow will replace this with:
          #   <your ACR login server>/frontend:latest
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  # MUST be 'frontend' to match the CD logs/S23 screenshot
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
