# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  # Use the secret you actually created
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node (optional build step)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install & build frontend if package.json exists
        run: |
          if [ -f frontend/package.json ]; then
            npm ci --prefix frontend
            npm --prefix frontend run build --if-present || true
          else
            echo "No package.json found in frontend/. Skipping npm build."
          fi

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          # az acr login expects the ACR NAME, not the FQDN
          ACR_NAME=$(echo "${{ env.ACR_LOGIN_SERVER }}" | cut -d. -f1)
          echo "Logging in to ACR: $ACR_NAME (from ${ACR_LOGIN_SERVER})"
          az acr login --name "$ACR_NAME"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push frontend image
        env:
          IMG_BASE: ${{ env.ACR_LOGIN_SERVER }}/frontend
        run: |
          # Requires a Dockerfile in ./frontend (see note below)
          docker build -t "$IMG_BASE:${{ env.IMAGE_TAG }}" -t "$IMG_BASE:latest" ./frontend
          docker push "$IMG_BASE:${{ env.IMAGE_TAG }}"
          docker push "$IMG_BASE:latest"

      - name: Logout from Azure
        if: always()
        run: az logout
