# week08/.github/workflows/frontend-cd.yml
name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag to deploy (default: latest)"
        required: false
        default: "latest"

env:
  # leave empty to use default namespace
  NAMESPACE: ""

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RG }}
          cluster-name:   ${{ secrets.AKS_CLUSTER }}

      - name: Deploy/Update k8s resources
        run: |
          # Apply your existing manifests (Deployment + Service)
          kubectl ${NAMESPACE:+-n $NAMESPACE} apply -f k8s/frontend.yaml

      - name: Roll to latest ACR image
        env:
          ACR: ${{ secrets.ACR_LOGIN_SERVER }}
          TAG: ${{ github.event.inputs.image_tag || 'latest' }}
        run: |
          IMG="${ACR}/frontend:${TAG}"
          kubectl ${NAMESPACE:+-n $NAMESPACE} set image deploy/frontend frontend="$IMG" --record
          kubectl ${NAMESPACE:+-n $NAMESPACE} rollout status deploy/frontend --timeout=300s

      - name: Show service
        run: kubectl ${NAMESPACE:+-n $NAMESPACE} get svc frontend -o wide
