name: PR CI

on:
  pull_request:
    branches: [ development, main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: pr-ci-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - service_name: product-service
            docker_context: example-1/backend/product_Service
          - service_name: frontend
            docker_context: example-1/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build images (no push)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker_context }}
          push: false
          tags: temp/${{ matrix.service_name }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
