name: Reusable CI

on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: backend
            path: backend
          - id: frontend
            path: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify path exists
        id: verify
        run: |
          if [ -d "${{ matrix.path }}" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: List files (if exists)
        if: steps.verify.outputs.exists == 'true'
        run: |
          echo "Directory: ${{ matrix.path }}"
          ls -la "${{ matrix.path }}"

      - name: No-op when missing
        if: steps.verify.outputs.exists != 'true'
        run: echo "No directory '${{ matrix.path }}' — skipping."

      - name: Finished
        run: echo "Reusable CI completed for '${{ matrix.path }}'."
